apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{  .Values.redis.host }}
  REDIS_PORT: {{  quote .Values.redis.port }}
  APACHE_RUN_USER: {{ .Values.apache.run.user }}
  APACHE_RUN_GROUP: {{ .Values.apache.run.group }}
  {{- with .Values.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
{{- if .Values.emptyCustomConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-custom
  labels:
    {{- include "app.labels" . | nindent 4 }}
data: null
{{- end }}
