version: '3.7'

volumes:
    postgres-data:
        driver: local

services:
    postgres:
        image: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - ${POSTGRES_PORT:-5432}:5432

    redis:
        image: redis

    private_api:
        build:
            context: ./api
            dockerfile: Dockerfile-private
        environment:
            APP_ENV: development
            DEBUG: ${DEBUG:-0}
            DB_HOST: postgres
            DB_DATABASE: postgres
            DB_USERNAME: ${PRIVATE_API_DB_USERNAME}
            DB_PASSWORD: ${PRIVATE_API_DB_PASSWORD}
            JWT_ENABLED: ${PRIVATE_API_JWT_ENABLED:-true}
            JWT_SECRET: ${PRIVATE_API_JWT_SECRET}
            JWT_SECURE: ${PRIVATE_API_JWT_SECURE}
        ports:
            - ${PRIVATE_API_PORT:-8081}:80
        volumes:
            - ./api/src/shared:/shared
            - ./api/src/private:/src
        depends_on:
            - postgres

    public_api:
        build:
            context: ./api
            dockerfile: Dockerfile-public
        environment:
            APP_ENV: development
            DEBUG: ${DEBUG:-0}
            DB_HOST: postgres
            DB_DATABASE: postgres
            DB_USERNAME: ${PUBLIC_API_DB_USERNAME}
            DB_PASSWORD: ${PUBLIC_API_DB_PASSWORD}
            REDIS_HOST: redis
            REDIS_PORT: 6379
        ports:
            - ${PUBLIC_API_PORT:-8082}:80
        volumes:
            - ./api/src/shared:/shared
            - ./api/src/public:/src
        depends_on:
            - postgres
            - redis

    healthauthority_api:
        build:
            context: ./api
            dockerfile: Dockerfile-healthauthority
        environment:
            APP_ENV: development
            DEBUG: ${DEBUG:-0}
            DB_HOST: postgres
            DB_DATABASE: postgres
            DB_USERNAME: ${HEALTHAUTHORITY_API_DB_USERNAME}
            DB_PASSWORD: ${HEALTHAUTHORITY_API_DB_PASSWORD}
        ports:
            - ${HEALTHAUTHORITY_API_PORT:-8083}:80
        volumes:
            - ./api/src/shared:/shared
            - ./api/src/healthauthority:/src
        depends_on:
            - postgres

    worker:
        build: worker
        environment:
            APP_ENV: development
            DEBUG: ${DEBUG:-0}
            DB_HOST: postgres
            DB_DATABASE: postgres
            DB_USERNAME: ${WORKER_DB_USERNAME}
            DB_PASSWORD: ${WORKER_DB_PASSWORD}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            HEALTHAUTHORITY_API_BASE_URI: http://healthauthority_api/v1/
        volumes:
            - ./worker/src:/src
        depends_on:
            - postgres
            - redis
            - healthauthority_api
