version: '3.7'

# ci overrides
services:
    private_api:
        environment:
            APP_ENV: test

    public_api:
        environment:
            APP_ENV: test

    worker:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED"

    healthauthority_api:
        environment:
            APP_ENV: test
            SECURITY_MODULE_TYPE: ${HEALTHAUTHORITY_SECURITY_MODULE_TYPE}
            SECURITY_MODULE_SK_KEY_EXCHANGE: ${HEALTHAUTHORITY_SECURITY_MODULE_SK_KEY_EXCHANGE}
            SECURITY_MODULE_SK_STORE: ${HEALTHAUTHORITY_SECURITY_MODULE_SK_STORE}

    healthauthority_api_cachekeys:
        environment:
            APP_ENV: test
            SECURITY_MODULE_TYPE: ${HEALTHAUTHORITY_SECURITY_MODULE_TYPE}
            SECURITY_MODULE_SK_KEY_EXCHANGE: ${HEALTHAUTHORITY_SECURITY_MODULE_SK_KEY_EXCHANGE}
            SECURITY_MODULE_SK_STORE: ${HEALTHAUTHORITY_SECURITY_MODULE_SK_STORE}

    portal:
        environment:
            APP_ENV: test
            
    bridge:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED"

    bridge-clients:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED"

    bridge-caseresults:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED" 