version: '3.7'

# test overrides
services:
    private_api:
        environment:
            APP_ENV: test
        volumes:
            - ./api/src/shared:/shared
            - ./api/src/private:/src

    public_api:
        environment:
            APP_ENV: test
        volumes:
            - ./api/src/shared:/shared
            - ./api/src/public:/src

    worker:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED"

    bridge:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED"

    bridge-clients:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED"

    bridge-caseresults:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED"

    healthauthority_api:
        environment:
            APP_ENV: test
            SECURITY_MODULE_TYPE: ${HEALTHAUTHORITY_SECURITY_MODULE_TYPE}
            SECURITY_MODULE_SK_KEY_EXCHANGE: ${HEALTHAUTHORITY_SECURITY_MODULE_SK_KEY_EXCHANGE}
            SECURITY_MODULE_SK_STORE: ${HEALTHAUTHORITY_SECURITY_MODULE_SK_STORE}
        volumes:
            - ./api/src/shared:/shared
            - ./api/src/healthauthority:/src

    healthauthority_api_cachekeys:
        environment:
            APP_ENV: test
            SECURITY_MODULE_TYPE: ${HEALTHAUTHORITY_SECURITY_MODULE_TYPE}
            SECURITY_MODULE_SK_KEY_EXCHANGE: ${HEALTHAUTHORITY_SECURITY_MODULE_SK_KEY_EXCHANGE}
            SECURITY_MODULE_SK_STORE: ${HEALTHAUTHORITY_SECURITY_MODULE_SK_STORE}
        volumes:
            - ./api/src/shared:/shared
            - ./api/src/healthauthority:/src

    portal:
        environment:
            APP_ENV: test
        volumes:
            - ./portal/src:/src