version: '3.7'

# test overrides
services:
    oracle:
        image: alpine
        entrypoint: ["echo", "Oracle database disabled"]
        restart: "no"

    private_api:
        environment:
            APP_ENV: test

    public_api:
        environment:
            APP_ENV: test

    worker:
        environment:
            APP_ENV: test

    healthauthority_api:
        environment:
            APP_ENV: test

    portal:
        environment:
            APP_ENV: test
       
