version: '3.7'

volumes:
    oracle-data:
        driver: local

services:
    oracle:
        image: ${ORACLE_IMAGE:-oracle/database:18.4.0-xe}
        volumes:
            - oracle-data:/opt/oracle/oradata
        environment:
            ORACLE_PWD: ${ORACLE_PASSWORD}

    sqlplus:
        image: ${ORACLE_IMAGE:-oracle/database:18.4.0-xe}
        entrypoint: sqlplus -L SYSTEM/"${ORACLE_PASSWORD}"@oracle/XEPDB1

    healthauthority_api:
        depends_on:
          - oracle

    portal:
        depends_on:
          - oracle
