version: '3.7'

services:
    private_api:
        environment:
            APP_ENV: development
        ports:
            - ${PRIVATE_API_PORT:-8081}:80
        volumes:
            - ./api/src/shared:/shared
            - ./api/src/private:/src

    public_api:
        environment:
            APP_ENV: development
        ports:
            - ${PUBLIC_API_PORT:-8082}:80
        volumes:
            - ./api/src/shared:/shared
            - ./api/src/public:/src

    worker:
        build: worker
        environment:
            APP_ENV: development
        volumes:
            - ./worker/src:/src

    healthauthority_api:
        environment:
            APP_ENV: development
        ports:
            - ${HEALTHAUTHORITY_API_PORT:-8083}:80
        volumes:
            - ./api/src/shared:/shared
            - ./api/src/healthauthority:/src

    portal:
        environment:
            APP_ENV: development
        ports:
            - ${PORTAL_PORT:-8084}:80
        volumes:
            - ./portal/src:/src

    pairing-worker:
        build: worker
        command: pairing:process-queue
        environment:
            DEBUG: ${DEBUG:-0}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            HEALTHAUTHORITY_API_BASE_URI: http://healthauthority_api/v1/
        depends_on:
            - redis
            - healthauthority_api