version: '3.7'

# development overrides
services:
    postgres:
        ports:
            - ${POSTGRES_PORT:-5432}:5432

    psql:
        image: postgres
        entrypoint: psql
        environment:
            PGPASSWORD: ${POSTGRES_PASSWORD}
            API_PASSWORD: ${API_PASSWORD}
            CONSOLE_PASSWORD: ${CONSOLE_PASSWORD}
