version: '3.7'

# ci overrides
services:
    private-api:
        environment:
            APP_ENV: test

    public-api:
        environment:
            APP_ENV: test

    worker:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED"

    healthauthority-api:
        environment:
            APP_ENV: test
            SECURITY_MODULE_TYPE: ${HEALTHAUTHORITY_SECURITY_MODULE_TYPE}
            SECURITY_MODULE_SK_KEY_EXCHANGE: ${HEALTHAUTHORITY_SECURITY_MODULE_SK_KEY_EXCHANGE}
            SECURITY_MODULE_SK_STORE: ${HEALTHAUTHORITY_SECURITY_MODULE_SK_STORE}

    healthauthority-hsm:
        environment:
            APP_ENV: test
            SECURITY_MODULE_TYPE: ${HEALTHAUTHORITY_SECURITY_MODULE_TYPE}
            SECURITY_MODULE_SK_KEY_EXCHANGE: ${HEALTHAUTHORITY_SECURITY_MODULE_SK_KEY_EXCHANGE}
            SECURITY_MODULE_SK_STORE: ${HEALTHAUTHORITY_SECURITY_MODULE_SK_STORE}
        volumes:
            - ./api/assets/healthauthority/cs_pkcs11_R2_keystore.cfg:/etc/utimaco/cs_pkcs11_R2.cfg

    portal:
        environment:
            APP_ENV: test
            
    bridge:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED"

    bridge-clients:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED"

    bridge-caseresults:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED" 