version: '3.7'

# development overrides
services:
    postgres:
        ports:
            - ${POSTGRES_PORT:-5432}:5432

    psql:
        image: postgres
        entrypoint: psql
        environment:
            PGPASSWORD: ${POSTGRES_PASSWORD}
            PRIVATE_API_DB_PASSWORD: ${PRIVATE_API_DB_PASSWORD}
            PUBLIC_API_DB_PASSWORD: ${PUBLIC_API_DB_PASSWORD}
            HEALTHAUTHORITY_API_DB_PASSWORD: ${HEALTHAUTHORITY_API_DB_PASSWORD}
            WORKER_DB_PASSWORD: ${WORKER_DB_PASSWORD}

    sqlplus:
        image: ${ORACLE_IMAGE:-oracle/database:18.4.0-xe}
        entrypoint: sqlplus -L SYSTEM/"${ORACLE_PASSWORD}"@oracle/XEPDB1