version: '3.7'

volumes:
    hsm-data:
        driver: local

services:
    redis:
        image: redis
        networks:
            - sluice

    redis-haa:
        image: redis
        networks:
            - healthauthority

    private-api:
        build:
            context: ./api
            dockerfile: Dockerfile-private
        environment:
            DEBUG: ${DEBUG:-0}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            JWT_ENABLED: ${PRIVATE_API_JWT_ENABLED:-true}
            JWT_SECRET: ${PRIVATE_API_JWT_SECRET}
            JWT_SECURE: ${PRIVATE_API_JWT_SECURE}
        depends_on:
            - redis
        networks:
            - private
            - sluice

    public-api:
        build:
            context: ./api
            dockerfile: Dockerfile-public
        environment:
            DEBUG: ${DEBUG:-0}
            REDIS_HOST: redis
            REDIS_PORT: 6379
        depends_on:
            - redis
        networks:
            - public
            - sluice

    bridge:
        build: bridge
        environment:
            DEBUG: ${DEBUG:-0}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            HEALTHAUTHORITY_API_BASE_URI: http://healthauthority-api:8080/v1/
        depends_on:
            - redis
            - healthauthority-api
        networks:
            - sluice
            - healthauthority

    bridge-clients:
        build: bridge
        command: /src/bridge process:clients
        environment:
            DEBUG: ${DEBUG:-0}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            HEALTHAUTHORITY_API_BASE_URI: http://healthauthority-api:8080/v1/
        depends_on:
            - redis
            - healthauthority-api
        networks:
            - sluice
            - healthauthority

    bridge-caseresults:
        build: bridge
        command: /src/bridge process:caseresults
        environment:
            DEBUG: ${DEBUG:-0}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            HEALTHAUTHORITY_API_BASE_URI: http://healthauthority-api:8080/v1/
        depends_on:
            - redis
            - healthauthority-api
        networks:
            - sluice
            - healthauthority

    worker:
        build: worker
        environment:
            DEBUG: ${DEBUG:-0}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            HEALTHAUTHORITY_API_BASE_URI: http://healthauthority-api:8080/v1/
        depends_on:
            - redis
            - healthauthority-api
        networks:
            - sluice
            - healthauthority
              
    healthauthority-api:
        build:
            context: ./api
            dockerfile: Dockerfile-healthauthority
        environment:
            DEBUG: ${DEBUG:-0}
            DB_TYPE: ${DATABASE_TYPE}
            DB_HOST: ${DATABASE_TYPE}
            DB_DATABASE: portal
            DB_USERNAME: ${HEALTHAUTHORITY_API_DB_USERNAME}
            DB_PASSWORD: ${HEALTHAUTHORITY_API_DB_PASSWORD}
            DB_TNS: ${HEALTHAUTHORITY_API_DB_TNS:-oracle/XEPDB1}
            REDIS_HOST: redis-haa
            REDIS_PORT: 6379
            PRIVATE_API_BASE_URI: http://private-api:8080/v1/
            PRIVATE_API_JWT_SECRET: ${PRIVATE_API_JWT_SECRET}
            SECURITY_MODULE_USER_PIN: ${HSM_USER_PIN}
            SECURITY_MODULE_SLOT_LABEL: "CryptoServer PKCS11 Token"
            SECURITY_MODULE_NONCE_USE_PHP_RANDOM_BYTES: 1
        volumes:
            - ./api/assets/healthauthority/cs_pkcs11_R2.cfg:/etc/utimaco/cs_pkcs11_R2.cfg
        networks:
            - healthauthority
            - private

    portal:
        build:
            context: ./portal
            dockerfile: Dockerfile
        environment:
            APP_URL: ${PORTAL_APP_URL}
            APP_KEY: ${PORTAL_APP_KEY}
            APP_DEBUG: ${DEBUG:-0}
            DB_CONNECTION: ${DATABASE_TYPE}
            DB_HOST: ${DATABASE_TYPE}
            DB_DATABASE: portal
            DB_USERNAME: ${PORTAL_DB_USERNAME}
            DB_PASSWORD: ${PORTAL_DB_PASSWORD}
            DB_TNS: ${PORTAL_DB_TNS:-oracle/XEPDB1}
            REDIS_HOST: redis-haa
            REDIS_PORT: 6379
            TIH_CLIENT_ID: ${PORTAL_TIH_CLIENT_ID}
            TIH_CLIENT_SECRET: ${PORTAL_TIH_CLIENT_SECRET}
            TIH_REDIRECT_URL: ${PORTAL_TIH_REDIRECT_URL}
            USER_ROLE_ADMIN: ${PORTAL_USER_ROLE_ADMIN:-DBCO-Beheer}
            USER_ROLE_USER: ${PORTAL_USER_ROLE_USER:-DBCO-Gebruiker}
            USER_ROLE_PLANNER: ${PORTAL_USER_ROLE_PLANNER:-DBCO-Werkverdeler}
            ALLOW_DEMO_LOGIN: ${PORTAL_ALLOW_DEMO_LOGIN}
            PRIVATE_API_BASE_URI: http://private-api:8080/v1/
            PRIVATE_API_JWT_SECRET: ${PRIVATE_API_JWT_SECRET}
            HEALTHAUTHORITY_API_BASE_URI: http://healthauthority-api:8080/v1/
        depends_on:
            - healthauthority-api
        networks:
            - healthauthority
            - private

    hsm:
        platform: linux/i386
        build:
            context: ../nl-covid19-dbco-app-hsm-private/hsm-simulator
            dockerfile: Dockerfile
        networks:
            - healthauthority

networks:
    public:
    sluice:
    private:
    healthauthority: