version: '3.7'

# ci overrides
services:
    private-api:
        environment:
            APP_ENV: test

    public-api:
        environment:
            APP_ENV: test

    worker:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED"

    healthauthority-api:
        environment:
            APP_ENV: test

    portal:
        environment:
            APP_ENV: test
            
    bridge:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED"

    bridge-clients:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED"

    bridge-caseresults:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED" 