version: '3.7'

volumes:
    mysql-data:
        driver: local
    hsm-data:
        driver: local

networks:
    public:
    sluice:
    private:
    healthauthority:

services:
    redis:
        extends:
            file: docker-compose/common.yml
            service: redis

    redis-haa:
        extends:
            file: docker-compose/common.yml
            service: redis-haa

    mysql:
        extends:
            file: docker-compose/common.yml
            service: mysql
        ports:
            - ${MYSQL_PORT:-3306}:3306

    private-api:
        extends:
            file: docker-compose/common.yml
            service: private-api
        depends_on:
            - redis
        ports:
            - ${PRIVATE_API_PORT:-8081}:8080
        volumes:
            - ./services/shared/library:/shared/library
            - ./services/shared/packages:/shared/packages
            - ./services/private-api/src:/src

    public-api:
        extends:
            file: docker-compose/common.yml
            service: public-api
        depends_on:
            - redis
        ports:
            - ${PUBLIC_API_PORT:-8082}:8080
        volumes:
            - ./services/shared/library:/shared/library
            - ./services/shared/packages:/shared/packages
            - ./services/public-api/src:/src

    bridge-clients:
        extends:
            file: docker-compose/common.yml
            service: bridge-clients
        depends_on:
            - redis
            - healthauthority-api
        volumes:
            - ./services/bridge/src:/src

    bridge-caseresults:
        extends:
            file: docker-compose/common.yml
            service: bridge-caseresults
        depends_on:
            - redis
            - healthauthority-api
        volumes:
            - ./services/bridge/src:/src

    healthauthority-api:
        extends:
            file: docker-compose/common.yml
            service: healthauthority-api
        depends_on:
            - mysql
            - redis-haa
            - sftp
        ports:
            - ${HEALTHAUTHORITY_API_PORT:-8083}:8080
        environment:
            METRICS_EXPORT_BASE_PATH: /metrics
            METRICS_SFTP_HOSTNAME: sftp
            METRICS_SFTP_USERNAME: sftp
            METRICS_SFTP_PRIVATE_KEY: /keys/id_rsa
            METRICS_SFTP_UPLOAD_PATH: /upload
        volumes:
            - ./services/shared/library:/shared/library
            - ./services/shared/packages:/shared/packages
            - ./services/healthauthority-api/src:/src
            - ./metrics/export:/metrics
            - type: bind
              source: ./sftp_id_rsa
              target: /keys/id_rsa
              read_only: true

    healthauthority-hsm:
        extends:
            file: docker-compose/common.yml
            service: healthauthority-hsm
        depends_on:
            - mysql
            - redis-haa
        volumes:
            - ./services/shared/library:/shared/library
            - ./services/shared/packages:/shared/packages
            - ./services/healthauthority-api/src:/src

    portal:
        extends:
            file: docker-compose/common.yml
            service: portal
        depends_on:
            - healthauthority-api
            - mysql
            - redis-haa
        build:
            args:
                - INSTALL_DEV_TOOLS=1
        ports:
            - ${PORTAL_PORT:-8084}:8080
        volumes:
            - ./services/portal/src:/src
            - ./services/shared/library:/shared/library
            - ./services/shared/packages:/shared/packages

    hsm:
        extends:
            file: docker-compose/common.yml
            service: hsm

    sftp:
        extends:
            file: docker-compose/common.yml
            service: sftp
        volumes:
            - ./metrics/sftp:/home/sftp/upload
            - type: bind
              source: ./sftp_id_rsa.pub
              target: /home/sftp/.ssh/keys/id_rsa.pub
              read_only: true
