version: '3.7'

services:
    private_api:
        environment:
            APP_ENV: development
        ports:
            - ${PRIVATE_API_PORT:-8081}:8080
        volumes:
            - ./api/src/shared:/shared
            - ./api/src/private:/src

    public_api:
        environment:
            APP_ENV: development
        ports:
            - ${PUBLIC_API_PORT:-8082}:8080
        volumes:
            - ./api/src/shared:/shared
            - ./api/src/public:/src

    worker:
        build: worker
        environment:
            APP_ENV: development
        volumes:
            - ./worker/src:/src

    bridge:
        build: bridge
        environment:
            APP_ENV: development
        volumes:
            - ./bridge/src:/src

    bridge-clients:
        build: bridge
        environment:
            APP_ENV: development
        volumes:
            - ./bridge/src:/src

    bridge-caseresults:
        build: bridge
        environment:
            APP_ENV: development
        volumes:
            - ./bridge/src:/src

    healthauthority_api:
        environment:
            APP_ENV: development
            SECURITY_MODULE_TYPE: ${HEALTHAUTHORITY_SECURITY_MODULE_TYPE:-simple}
            SECURITY_MODULE_SK_KEY_EXCHANGE: ${HEALTHAUTHORITY_SECURITY_MODULE_SK_KEY_EXCHANGE}
            SECURITY_MODULE_SK_STORE: ${HEALTHAUTHORITY_SECURITY_MODULE_SK_STORE}
        ports:
            - ${HEALTHAUTHORITY_API_PORT:-8083}:8080
        volumes:
            - ./api/src/shared:/shared
            - ./api/src/healthauthority:/src

    portal:
        environment:
            APP_ENV: development
        ports:
            - ${PORTAL_PORT:-8084}:8080
        volumes:
            - ./portal/src:/src

    simulator:
        build: simulator
        environment:
            APP_ENV: development
            DEBUG: ${DEBUG:-0}
            PUBLIC_API_BASE_URI: http://public_api:8080/v1/
            HEALTHAUTHORITY_SK_KEY_EXCHANGE: ${HEALTHAUTHORITY_SECURITY_MODULE_SK_KEY_EXCHANGE}
        depends_on:
            - public_api
        volumes:
            - ./simulator/src:/src
        networks:
            - public