version: '3.7'

# test overrides
services:
    postgres:
        ports:
            - ${POSTGRES_PORT:-5432}:5432
    psql:
        image: postgres
        entrypoint: psql
        environment:
            PGPASSWORD: ${POSTGRES_PASSWORD}
            PRIVATE_API_DB_PASSWORD: ${PRIVATE_API_DB_PASSWORD}
            PUBLIC_API_DB_PASSWORD: ${PUBLIC_API_DB_PASSWORD}
            HEALTHAUTHORITY_API_DB_PASSWORD: ${HEALTHAUTHORITY_API_DB_PASSWORD}
            CONSOLE_DB_PASSWORD: ${CONSOLE_DB_PASSWORD}
        depends_on:
            - postgres

    private_api:
        environment:
            APP_ENV: test

    public_api:
        environment:
            APP_ENV: test

    healthauthority_api:
        environment:
            APP_ENV: test

    console:
        environment:
            APP_ENV: test
  
    portal:
        environment:
            APP_ENV: test
       
