/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */

export type AlertElementOptionsVariant = typeof AlertElementOptionsVariant[keyof typeof AlertElementOptionsVariant];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlertElementOptionsVariant = {
  success: 'success',
  info: 'info',
  warning: 'warning',
  error: 'error',
} as const;
