/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { CommonTypeOptions } from './commonTypeOptions';
import type { UiSchema } from './uiSchema';

export type ArrayOptions = CommonTypeOptions & {
  addLabel?: string;
  /** Show sort buttons for array items, default is false */
  showSortButtons?: boolean;
  noDataLabel?: string;
  detail?: UiSchema;
};
