/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { UiSchemaElement } from './uiSchemaElement';
import type { Scoped } from './scoped';

export type BaseControlElement = UiSchemaElement & Scoped & {
  label?: string;
  i18n?: string;
};
