/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */

/**
 * BCO Phase
 */
export type BCOPhase = typeof BCOPhase[keyof typeof BCOPhase];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BCOPhase = {
  none: 'none',
  NUMBER_1: '1',
  NUMBER_2: '2',
  NUMBER_3: '3',
  NUMBER_4: '4',
  NUMBER_5: '5',
  steekproef: 'steekproef',
} as const;
