/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */

export type BCOStatus = typeof BCOStatus[keyof typeof BCOStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BCOStatus = {
  unknown: 'unknown',
  draft: 'draft',
  open: 'open',
  completed: 'completed',
  archived: 'archived',
} as const;
