/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */

export type CaseAssignmentOptionTypeMenuType = typeof CaseAssignmentOptionTypeMenuType[keyof typeof CaseAssignmentOptionTypeMenuType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CaseAssignmentOptionTypeMenuType = {
  menu: 'menu',
} as const;
