/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */

export type CaseAssignment = (unknown & {
  caseListUuid?: string;
  assignedUserUuid?: string;
  assignedCaseListUuid?: string;
  assignedOrganisationUuid?: string;
  staleSince: string;
}) | (unknown & {
  caseListUuid?: string;
  assignedUserUuid?: string;
  assignedCaseListUuid?: string;
  assignedOrganisationUuid?: string;
  staleSince: string;
}) | (unknown & {
  caseListUuid?: string;
  assignedUserUuid?: string;
  assignedCaseListUuid?: string;
  assignedOrganisationUuid?: string;
  staleSince: string;
}) | (unknown & {
  caseListUuid?: string;
  assignedUserUuid?: string;
  assignedCaseListUuid?: string;
  assignedOrganisationUuid?: string;
  staleSince: string;
});
