/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { CaseAssignment } from './caseAssignment';
import type { CasesAssignmentBodyAllOf } from './casesAssignmentBodyAllOf';

export type CasesAssignmentBody = CaseAssignment & CasesAssignmentBodyAllOf;
