/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { CaseAssignmentOptionTypeOptionAssignmentAssignedCaseListUuid } from './caseAssignmentOptionTypeOptionAssignmentAssignedCaseListUuid';
import type { CaseAssignmentOptionTypeOptionAssignmentAssignedOrganisationUuid } from './caseAssignmentOptionTypeOptionAssignmentAssignedOrganisationUuid';
import type { CaseAssignmentOptionTypeOptionAssignmentAssignedUserUuid } from './caseAssignmentOptionTypeOptionAssignmentAssignedUserUuid';

export type CaseAssignmentOptionTypeOptionAssignment = (unknown & {
  assignedCaseListUuid?: CaseAssignmentOptionTypeOptionAssignmentAssignedCaseListUuid;
  assignedOrganisationUuid?: CaseAssignmentOptionTypeOptionAssignmentAssignedOrganisationUuid;
  assignedUserUuid?: CaseAssignmentOptionTypeOptionAssignmentAssignedUserUuid;
}) | (unknown & {
  assignedCaseListUuid?: CaseAssignmentOptionTypeOptionAssignmentAssignedCaseListUuid;
  assignedOrganisationUuid?: CaseAssignmentOptionTypeOptionAssignmentAssignedOrganisationUuid;
  assignedUserUuid?: CaseAssignmentOptionTypeOptionAssignmentAssignedUserUuid;
}) | (unknown & {
  assignedCaseListUuid?: CaseAssignmentOptionTypeOptionAssignmentAssignedCaseListUuid;
  assignedOrganisationUuid?: CaseAssignmentOptionTypeOptionAssignmentAssignedOrganisationUuid;
  assignedUserUuid?: CaseAssignmentOptionTypeOptionAssignmentAssignedUserUuid;
});
