/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { CaseAssignmentOptionTypeOptionType } from './caseAssignmentOptionTypeOptionType';
import type { CaseAssignmentOptionTypeOptionAssignmentType } from './caseAssignmentOptionTypeOptionAssignmentType';
import type { CaseAssignmentOptionTypeOptionAssignment } from './caseAssignmentOptionTypeOptionAssignment';

export interface CaseAssignmentOptionTypeOption {
  type: CaseAssignmentOptionTypeOptionType;
  label: string;
  isSelected: boolean;
  isEnabled: boolean;
  isQueue?: boolean;
  assignmentType?: CaseAssignmentOptionTypeOptionAssignmentType;
  assignment: CaseAssignmentOptionTypeOptionAssignment;
}
