/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */

export type CategoryElementType = typeof CategoryElementType[keyof typeof CategoryElementType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryElementType = {
  Category: 'Category',
} as const;
