/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */

export type ChildFormControlElementCustomRenderer = typeof ChildFormControlElementCustomRenderer[keyof typeof ChildFormControlElementCustomRenderer];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChildFormControlElementCustomRenderer = {
  ChildForm: 'ChildForm',
  ChildFormCollection: 'ChildFormCollection',
} as const;
