/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { StringOptions } from './stringOptions';
import type { BooleanOptions } from './booleanOptions';
import type { ArrayOptions } from './arrayOptions';
import type { EnumOptions } from './enumOptions';

export type ControlElementOptions = StringOptions | BooleanOptions | ArrayOptions | EnumOptions;
