/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { BaseCustomControlElement } from './baseCustomControlElement';
import type { CustomControlElementCustomRenderer } from './customControlElementCustomRenderer';

export type CustomControlElement = BaseCustomControlElement & {
  customRenderer?: CustomControlElementCustomRenderer;
};
