/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */

export type CustomControlElementCustomRenderer = typeof CustomControlElementCustomRenderer[keyof typeof CustomControlElementCustomRenderer];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomControlElementCustomRenderer = {
  Message: 'Message',
  JsonEditor: 'JsonEditor',
  RadioButtonGroup: 'RadioButtonGroup',
  Table: 'Table',
  FormLink: 'FormLink',
  ChildForm: 'ChildForm',
  ChildFormCollection: 'ChildFormCollection',
} as const;
