/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { PlaceHolderOption } from './placeHolderOption';
import type { CommonTypeOptions } from './commonTypeOptions';
import type { EnumOptionsFormat } from './enumOptionsFormat';

export type EnumOptions = PlaceHolderOption & CommonTypeOptions & {
  format?: EnumOptionsFormat;
};
