/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */

export type EnumOptionsFormat = typeof EnumOptionsFormat[keyof typeof EnumOptionsFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnumOptionsFormat = {
  radio: 'radio',
  'radio-button': 'radio-button',
} as const;
