/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { FormValidationErrorParams } from './formValidationErrorParams';

/**
 * Form error object, a partial type of the AJV error object. See https://jsonforms.io/docs/validation#external-validation-errors
 */
export interface FormValidationError {
  schemaPath?: string;
  instancePath: string;
  keyword?: string;
  message: string;
  params?: FormValidationErrorParams;
}
