/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { Url } from './url';
import type { FormRequestConfigMethod } from './formRequestConfigMethod';

export interface FormRequestConfig {
  href: Url;
  /** HTTP method to use for the request, defaults to GET */
  method?: FormRequestConfigMethod;
}
