/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */

/**
 * HTTP method to use for the request, defaults to GET
 */
export type FormRequestConfigMethod = typeof FormRequestConfigMethod[keyof typeof FormRequestConfigMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormRequestConfigMethod = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  PATCH: 'PATCH',
  DELETE: 'DELETE',
} as const;
