/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { FormRequestConfig } from './formRequestConfig';

/**
 * An object with links to that is used by the form to perform CRUD actions
 */
export type FormMetaDataLinks = {
  self?: FormRequestConfig;
  create?: FormRequestConfig;
  update?: FormRequestConfig;
  delete?: FormRequestConfig;
};
