/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { JsonSchemaDraft07 } from './jsonSchemaDraft07';
import type { StringArray } from './stringArray';

export type JsonSchemaDraft07Dependencies = {[key: string]: JsonSchemaDraft07 | StringArray};
