/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { JsonSchemaDraft07 } from './jsonSchemaDraft07';

export type JsonSchemaDraft07Definitions = {[key: string]: JsonSchemaDraft07};
