/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { NonNegativeInteger } from './nonNegativeInteger';

export type NonNegativeIntegerDefault0 = NonNegativeInteger & unknown;
