/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */

export type PlannerView = typeof PlannerView[keyof typeof PlannerView];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlannerView = {
  unknown: 'unknown',
  unassigned: 'unassigned',
  assigned: 'assigned',
  outsourced: 'outsourced',
  queued: 'queued',
  archived: 'archived',
  completed: 'completed',
} as const;
