/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */

export type Priority = typeof Priority[keyof typeof Priority];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Priority = {
  NUMBER_3: 3,
  NUMBER_2: 2,
  NUMBER_1: 1,
  NUMBER_0: 0,
} as const;
