/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { RuleEffect } from './ruleEffect';
import type { RuleCondition } from './ruleCondition';

export interface Rule {
  effect: RuleEffect;
  /** The condition that must be met for the effect to be applied. Note that this schema is not complete, conditions can for example be nested. To keep things simple we currently only support a flat list of conditions.
 */
  condition?: RuleCondition;
}
