/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { RuleConditionOneOfType } from './ruleConditionOneOfType';
import type { SchemaBasedCondition } from './schemaBasedCondition';

export type RuleConditionOneOf = {
  type: RuleConditionOneOfType;
  conditions: SchemaBasedCondition[];
};
