/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */

export type RuleEffect = typeof RuleEffect[keyof typeof RuleEffect];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RuleEffect = {
  HIDE: 'HIDE',
  SHOW: 'SHOW',
  ENABLE: 'ENABLE',
  DISABLE: 'DISABLE',
} as const;
