/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */

export type SimpleTypes = typeof SimpleTypes[keyof typeof SimpleTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SimpleTypes = {
  array: 'array',
  boolean: 'boolean',
  integer: 'integer',
  null: 'null',
  number: 'number',
  object: 'object',
  string: 'string',
} as const;
