/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */

export type StatusIndexContactTracing = typeof StatusIndexContactTracing[keyof typeof StatusIndexContactTracing];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusIndexContactTracing = {
  unknown: 'unknown',
  not_approached: 'not_approached',
  not_reachable: 'not_reachable',
  conversation_started: 'conversation_started',
  closed_outside_ggd: 'closed_outside_ggd',
  closed_no_collaboration: 'closed_no_collaboration',
  completed: 'completed',
  new: 'new',
  not_started: 'not_started',
  two_times_not_reached: 'two_times_not_reached',
  callback_request: 'callback_request',
  loose_end: 'loose_end',
  four_times_not_reached: 'four_times_not_reached',
  bco_finished: 'bco_finished',
  closed: 'closed',
} as const;
