/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * DBCO Portal
 * API used for the portal for healthcare (BCO) workers
 * OpenAPI spec version: 1.0.0
 */
import type { LayoutElement } from './layoutElement';
import type { GroupElement } from './groupElement';
import type { CategoryElement } from './categoryElement';
import type { AlertElement } from './alertElement';
import type { ControlElement } from './controlElement';
import type { CustomControlElement } from './customControlElement';
import type { ChildFormControlElement } from './childFormControlElement';

export type UiSchema = LayoutElement | GroupElement | CategoryElement | AlertElement | ControlElement | CustomControlElement | ChildFormControlElement;
