<?php

declare(strict_types=1);

use MinVWS\DBCO\Enum\Models\Permission;

    // Permission documentation: https://egeniq.atlassian.net/wiki/spaces/GGD/pages/2224947309/Permissions

$caseEditPermissions = [
    Permission::caseUserEdit(),
    Permission::caseEditContactStatus(),
    Permission::caseBcoPhaseEdit(),
    Permission::contextCreate(),
    Permission::contextEdit(),
    Permission::contextDelete(),
    Permission::contextLink(),
    Permission::taskCreate(),
    Permission::taskEdit(),
    Permission::taskUserDelete(),
    Permission::caseBsnLookup(),
    Permission::caseAddressLookup(),
    Permission::caseViewUserTimeline(),
    Permission::caseViewOsirisHistory(),
    Permission::caseCreateCallToAction(),
    Permission::organisationList(),
    Permission::placeCreate(),
    Permission::placeEdit(),
    Permission::placeEditOwnedByOrganisation(),
    Permission::placeEditNotOwnedByOrganisation(),
    Permission::placeSearch(),
    Permission::placeSectionList(),
    Permission::placeSectionCreate(),
    Permission::placeSectionCreateOwnedByOrganisation(),
    Permission::placeSectionCreateNotOwnedByOrganisation(),
    Permission::choreList(),
    Permission::callToAction(),
];

return [

    'user' => [
        ...$caseEditPermissions,
        Permission::caseCreate(),
        Permission::caseListUserCases(),
        Permission::caseExport(),
        Permission::caseCanPickUpNew(),
        Permission::caseCanBeAssignedToOpen(),
        Permission::caseCanBeAssignedToUnknown(),
        Permission::caseCanBeAssignedToDraft(),
        Permission::caseCanBeAssignedToArchived(),
        Permission::caseViewCallToAction(),
        Permission::datacatalog(),
    ],
    'user_nationwide' => [
        ...$caseEditPermissions,
        Permission::caseListUserCases(),
        Permission::caseExport(),
        Permission::caseCanPickUpNew(),
        Permission::caseCanBeAssignedToOpen(),
        Permission::caseCanBeAssignedToUnknown(),
        Permission::caseCanBeAssignedToDraft(),
        Permission::caseCanBeAssignedToArchived(),
        Permission::caseViewCallToAction(),
        Permission::datacatalog(),
    ],
    'planner' => [
        Permission::caseListPlannerCases(),
        Permission::caseCreate(),
        Permission::casePlannerEdit(),
        Permission::casePlannerDelete(),
        Permission::caseBsnLookup(),
        Permission::caseSearch(),
        Permission::caseAddressLookup(),
        Permission::caseArchive(),
        Permission::caseReopen(),
        Permission::caseBcoPhaseEdit(),
        Permission::intakeList(),
        Permission::caseArchiveDirectly(),
        Permission::caseEditContactStatus(),
        Permission::placeSectionList(),
        Permission::organisationUpdate(),
        Permission::organisationList(),
        Permission::caseViewPlannerTimeline(),
        Permission::caseViewOsirisHistory(),
        Permission::choreList(),
        Permission::datacatalog(),
        Permission::caseMetricsList(),
    ],
    'planner_nationwide' => [
        Permission::caseListPlannerCases(),
        Permission::casePlannerEdit(),
        Permission::casePlannerDelete(),
        Permission::caseBsnLookup(),
        Permission::caseSearch(),
        Permission::caseAddressLookup(),
        Permission::caseArchive(),
        Permission::caseReopen(),
        Permission::caseBcoPhaseEdit(),
        Permission::intakeList(),
        Permission::caseArchiveDirectly(),
        Permission::caseEditContactStatus(),
        Permission::placeSectionList(),
        Permission::organisationUpdate(),
        Permission::organisationList(),
        Permission::caseViewPlannerTimeline(),
        Permission::caseViewOsirisHistory(),
        Permission::choreList(),
        Permission::datacatalog(),
    ],
    'compliance' => [
        Permission::caseListAccessRequests(),
        Permission::caseViewAccessRequest(),
        Permission::taskViewAccessRequest(),
        Permission::caseComplianceDelete(),
        Permission::taskComplianceDelete(),
        Permission::caseRestore(),
        Permission::taskRestore(),
        Permission::choreList(),
        Permission::datacatalog(),
    ],
    'contextmanager' => [],
    'clusterspecialist' => [
        ...$caseEditPermissions,
        Permission::placeList(),
        Permission::placeMerge(),
        Permission::placeDelete(),
        Permission::placeVerify(),
        Permission::placeCaseList(),
        Permission::placeSectionEdit(),
        Permission::placeSectionEditOwnedByOrganisation(),
        Permission::placeSectionDelete(),
        Permission::placeSectionMerge(),
        Permission::contextList(),
        Permission::datacatalog(),
        Permission::callcenterView(),
        Permission::caseEditViaSearchCase(),
        Permission::addCasesByChore(),
    ],
    'casequality' => [
        ...$caseEditPermissions,
        Permission::caseApprove(),
        Permission::caseArchive(),
        Permission::caseListUserCases(),
        Permission::caseCanBeAssignedToCompleted(),
        Permission::caseExport(),
        Permission::contextList(),
        Permission::datacatalog(),
    ],
    'casequality_nationwide' => [
        ...$caseEditPermissions,
        Permission::caseApprove(),
        Permission::caseArchive(),
        Permission::caseListUserCases(),
        Permission::caseCanBeAssignedToCompleted(),
        Permission::caseExport(),
        Permission::contextList(),
        Permission::datacatalog(),
    ],
    'conversation_coach' => [
        Permission::caseViewSupervisionRegional(),
        Permission::caseViewUserTimeline(),
        Permission::caseViewOsirisHistory(),
        Permission::expertQuestionConversationCoach(),
        Permission::expertQuestionList(),
        Permission::expertQuestionAssign(),
        Permission::expertQuestionAnswer(),
        Permission::choreList(),
        Permission::datacatalog(),
    ],
    'conversation_coach_nationwide' => [
        Permission::caseViewSupervisionRegional(),
        Permission::caseViewUserTimeline(),
        Permission::caseViewOsirisHistory(),
        Permission::expertQuestionConversationCoach(),
        Permission::expertQuestionList(),
        Permission::expertQuestionAssign(),
        Permission::expertQuestionAnswer(),
        Permission::choreList(),
        Permission::datacatalog(),
    ],
    'medical_supervisor' => [
        Permission::caseViewSupervisionRegional(),
        Permission::caseViewUserTimeline(),
        Permission::caseViewOsirisHistory(),
        Permission::expertQuestionMedicalSupervisor(),
        Permission::expertQuestionList(),
        Permission::expertQuestionAssign(),
        Permission::expertQuestionAnswer(),
        Permission::choreList(),
        Permission::datacatalog(),
    ],
    'medical_supervisor_nationwide' => [
        Permission::caseViewSupervisionNationwide(),
        Permission::caseViewUserTimeline(),
        Permission::caseViewOsirisHistory(),
        Permission::expertQuestionMedicalSupervisor(),
        Permission::expertQuestionList(),
        Permission::expertQuestionAssign(),
        Permission::expertQuestionAnswer(),
        Permission::choreList(),
        Permission::datacatalog(),
    ],
    'callcenter' => [
        Permission::callcenterView(),
        Permission::datacatalog(),
        Permission::caseCreateNote(),
        Permission::createCallToActionViaSearchCase(),
    ],
    'callcenter_expert' => [
        ...$caseEditPermissions,
        Permission::callcenterView(),
        Permission::caseEditViaSearchCase(),
        Permission::datacatalog(),
        Permission::addCasesByChore(),
        // phpcs:ignore Generic.Commenting.Todo.TaskFound -- baseline
        // Permission::caseExport(), // TODO is this needed?
    ],
    'datacatalog' => [
        Permission::datacatalog(),
    ],
    'admin' => [
        Permission::adminView(),
        Permission::adminPolicyAdviceModule(),
    ],
];
