<?php

declare(strict_types=1);

use App\Models\Context;
use App\Models\CovidCase;
use App\Models\Eloquent;
use App\Models\Event;
use App\Models\Person;
use App\Models\Shared;
use App\Models\Task;
use App\Models\TestResult;

return [
    'output' => [
        'json' => 'resources/schemas/json',
    ],
    'classes' => [
        Context\Circumstances::class,
        Context\Contact::class,
        Context\General::class,
        Context\Moment::class,
        CovidCase\Abroad::class,
        CovidCase\AlternateContact::class,
        CovidCase\AlternateResidency::class,
        CovidCase\AlternativeLanguage::class,
        CovidCase\Communication::class,
        CovidCase\Contact::class,
        CovidCase\Contacts::class,
        CovidCase\Deceased::class,
        CovidCase\EduDaycare::class,
        CovidCase\ExtensiveContactTracing::class,
        CovidCase\General::class,
        CovidCase\GeneralPractitioner::class,
        CovidCase\GeneralPractitionerAddress::class,
        CovidCase\GroupTransport::class,
        CovidCase\Hospital::class,
        CovidCase\Housemates::class,
        CovidCase\Immunity::class,
        CovidCase\Index::class,
        CovidCase\IndexAddress::class,
        CovidCase\Job::class,
        CovidCase\Medication::class,
        CovidCase\Medicine::class,
        CovidCase\Pregnancy::class,
        CovidCase\PrincipalContextualSettings::class,
        CovidCase\RecentBirth::class,
        CovidCase\RiskLocation::class,
        CovidCase\SourceEnvironments::class,
        CovidCase\Symptoms::class,
        CovidCase\Test::class,
        CovidCase\Trip::class,
        CovidCase\UnderlyingSuffering::class,
        CovidCase\Vaccination::class,
        Eloquent\CaseList::class,
        Eloquent\CaseUpdate::class,
        Eloquent\CaseUpdateContact::class,
        Eloquent\CaseUpdateContactFragment::class,
        Eloquent\CaseUpdateFragment::class,
        Eloquent\Context::class,
        Eloquent\EloquentCase::class,
        Eloquent\EloquentOrganisation::class,
        Eloquent\EloquentTask::class,
        Eloquent\EloquentUser::class,
        Eloquent\Intake::class,
        Eloquent\IntakeContact::class,
        Eloquent\IntakeContactFragment::class,
        Eloquent\IntakeFragment::class,
        Eloquent\Person::class,
        Eloquent\Place::class,
        Eloquent\Section::class,
        Eloquent\TestResult::class,
        Eloquent\TestResultRaw::class,
        Event::class,
        Person\ContactDetails::class,
        Person\NameAndAddress::class,
        Shared\Address::class,
        Shared\VaccineInjection::class,
        Task\AlternateContact::class,
        Task\AlternativeLanguage::class,
        Task\Circumstances::class,
        Task\General::class,
        Task\Immunity::class,
        Task\Inform::class,
        Task\Job::class,
        Task\PersonalDetails::class,
        Task\Symptoms::class,
        Task\TaskAddress::class,
        Task\Test::class,
        Task\Vaccination::class,
        TestResult\General::class,
    ],
    'root' => [
        Eloquent\EloquentCase::class,
        Eloquent\Place::class,
        Event::class,
    ],
    'readTranslationsFrom' => __DIR__ . '/../resources/data/datacatalog.csv',
    'overrideCaseVersion' => env('SCHEMA_ELOQUENTCASE_VERSION'),
];
