apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  DEBUG: {{ quote .Values.debug }}
  REDIS_HOST: {{  .Values.redis.host }}
  REDIS_PORT: {{  quote .Values.redis.port }}
  {{- if .Values.redis.sentinel.service }}
  REDIS_SENTINEL_SERVICE: {{ .Values.redis.sentinel.service }}
  {{- end }}
  HEALTHAUTHORITY_API_BASE_URI: {{  .Values.healthauthority.api.base_uri }}