apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  DEBUG: {{ quote .Values.debug }}
  REDIS_HOST: {{  .Values.redis.host }}
  REDIS_PORT: {{  quote .Values.redis.port }}
  {{- if .Values.redis.sentinel.service }}
  REDIS_SENTINEL_SERVICE: {{ .Values.redis.sentinel.service }}
  {{- end }}
  SECURITY_MODULE_TYPE: {{ .Values.security.module.type }}
  SECURITY_MODULE_NONCE_USE_PHP_RANDOM_BYTES: {{ .Values.security.module.nonce_use_php_random_bytes }}