{{- if eq .Values.security.module.type "hsm"}}
{{- if (not .Values.security.module.hsm.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  SECURITY_MODULE_SLOT_LABEL: {{ .Values.security.module.hsm.slot.label | b64enc | quote }}
  SECURITY_MODULE_USER_PIN: {{ .Values.security.module.hsm.user.pin | b64enc | quote }}
{{- end }}
{{- end }}