#!/usr/bin/env bash

set -exo pipefail

php artisan rabbitmq:setup

if [ "$QA_RESET_DB" = "true" ]; then
    php artisan db:wipe --force --no-interaction
fi

php artisan migrate --force --no-interaction

if [ "$QA_RESET_DB" = "true" ]; then
    php artisan db:seed --force --no-interaction
    php artisan db:seed --class DummySeeder --force --no-interaction
    php artisan db:seed --class DummyZipcodeSeeder --force --no-interaction

    php artisan import:zipcodes
    php artisan test-result-import:manage enable --all-organisations
fi

if [ "$QA_GENERATE_TEST_DATA" = "true" ]; then
    php artisan test-data:generate
fi
