apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.env | nindent 2 }}
---
{{- if .Values.emptyCustomConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-custom
  labels:
    {{- include "app.labels" . | nindent 4 }}
data: null
{{- end }}
