apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  APP_DEBUG: {{ quote .Values.app.debug }}
  APP_URL: {{  .Values.app.url }}
  APACHE_RUN_USER: {{  .Values.apache.run.user }}
  REDIS_HOST: {{  .Values.redis.host }}
  REDIS_PORT: {{  quote .Values.redis.port }}
  DB_CONNECTION: {{  .Values.db.type }}
  DB_HOST: {{ .Values.db.host }}
  DB_DATABASE: {{ .Values.db.database }}
  DB_USERNAME: {{ .Values.db.username }}
  TIH_REDIRECT_URL: {{ .Values.tih.redirect_url }}
  TIH_CLIENT_ID: {{ .Values.tih.client_id }}
  PRIVATE_API_BASE_URI: {{ .Values.private.jwt.base_uri }}
  USER_ROLE_ADMIN: {{ .Values.user.role.admin }}
  USER_ROLE_USER: {{ .Values.user.role.user }}
  USER_ROLE_PLANNER: {{ .Values.user.role.planner }}