{{- range $job := .Values.cronJobs }}
{{- if $job.enabled }}
---
{{- if semverCompare "<1.21-0" $.Capabilities.KubeVersion.Version }}
apiVersion: batch/v1beta1
{{- else }}
apiVersion: batch/v1
{{- end }}
kind: CronJob
metadata:
  name: {{ template "app.fullname" $ }}-{{ $job.name }}
  labels:
    app.kubernetes.io/name: {{ include "app.fullname" $ }}-{{ $job.name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  schedule: {{ $job.cronjob.schedule }}
  successfulJobsHistoryLimit: {{ $job.cronjob.successfulJobsHistoryLimit }}
  concurrencyPolicy: {{ $job.cronjob.concurrencyPolicy }}
  jobTemplate:
    spec:
      backoffLimit: {{ $job.cronjob.backoffLimit }}
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "app.fullname" $ }}-{{ $job.name }}
        spec:
          {{- if $.Values.serviceAccount.enabled }}
          serviceAccountName: {{ template "app.serviceAccountName" $ }}
          {{- end }}
          {{- if $.Values.imagePullSecrets }}
          imagePullSecrets:
            - name: {{ $.Values.imagePullSecrets }}
          {{- end }}
          containers:
            - name: {{ $.Chart.Name }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command: ["/bin/sh","-c"]
              args:
              - >-
                {{- range $job.cronjob.args }}
                  {{ . }}
                {{- end }}
              {{- with $job.env }}
              securityContext:
{{ toYaml .Values.containerSecurityContext | indent 16 }}
              env:
              {{- tpl . $ | nindent 16 }}
              {{- end }}
              envFrom:
              - configMapRef:
                  name: {{ template "app.fullname" $ }}
              - secretRef:
                  name: {{ template "app.fullname" $ }}
                  optional: true
              - secretRef:
                  name: {{ template "app.fullname" $ }}-{{ $job.name }}
                  optional: true
              - configMapRef:
                  name: {{ template "app.fullname" $ }}-custom
                  optional: true
              - secretRef:
                  name: {{ template "app.fullname" $ }}-custom
                  optional: true
              - secretRef:
                  name: {{ template "app.fullname" $ }}-{{ $job.name }}-custom
                  optional: true
              resources:
{{ toYaml $.Values.resources | indent 16 }}
              {{- with $job.volumeMounts }}
              volumeMounts:
              {{- tpl . $ | nindent 16 }}
              {{- end }}
          restartPolicy: {{ $job.cronjob.restartPolicy }}
        {{- with $.Values.securityContext }}
          securityContext:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with $.Values.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with $.Values.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with $.Values.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with $job.volumes }}
          volumes:
          {{- tpl . $ | nindent 12 }}
        {{- end }}
{{- end }}
{{- end }}