{{- if semverCompare "<1.21-0" $.Capabilities.KubeVersion.Version }}
apiVersion: batch/v1beta1
{{- else }}
apiVersion: batch/v1
{{- end }}
kind: CronJob
metadata:
  name: {{ template "app.fullname" . }}-scheduler
  labels:
    app.kubernetes.io/name: {{ include "app.fullname" . }}-scheduler
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- with .Values.scheduler }}
  schedule: {{ quote .schedule }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "app.fullname" . }}-scheduler
        spec:
          {{- if .Values.serviceAccount.enabled }}
          serviceAccountName: {{ template "app.serviceAccountName" . }}
          {{- end }}
          {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
            - name: {{ .Values.imagePullSecrets }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}-scheduler
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["php"]
              args: ["artisan", "schedule:run"]
              securityContext:
{{ toYaml .Values.containerSecurityContext | indent 16 }}
              envFrom:
              - configMapRef:
                  name: {{ template "app.fullname" . }}
              - secretRef:
                  name: {{ template "app.fullname" . }}
              - configMapRef:
                  name: {{ template "app.fullname" . }}-custom
                  optional: true
              - secretRef:
                  name: {{ template "app.fullname" . }}-custom
                  optional: true
              resources:
{{ toYaml .Values.resources | indent 16 }}
              {{- with .Values.volumeMounts }}
              volumeMounts:
              {{- tpl . $ | nindent 16 }}
              {{- end }}
          restartPolicy: {{ .Values.scheduler.restartPolicy }}
        {{- with .Values.securityContext }}
          securityContext:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.volumes }}
          volumes:
          {{- tpl . $ | nindent 12 }}
        {{- end }}
