{{- if .Values.defaultWorker.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-default-worker
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: default-worker
data:
  {{- with .Values.defaultWorker.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}