{{- if .Values.defaultWorker.enabled -}}
{{- if .Values.defaultWorker.envSecrets -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-default-worker
  labels:
    app.kubernetes.io/name: {{ include "app.fullname" . }}-default-worker
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{- toYaml .Values.defaultWorker.envSecrets | nindent 2 }}
{{- end }}
{{- end }}