{{- if .Values.defaultWorker.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}-default-worker
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: default-worker
spec:
  replicas: {{ .Values.defaultWorker.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.fullname" . }}
      app.kubernetes.io/component: default-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.fullname" . }}
        app.kubernetes.io/component: default-worker
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/default-worker-configmap.yaml") . | sha256sum }}
        {{- range $key, $value := .Values.defaultWorker.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.defaultWorker.terminationGracePeriodSeconds }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ template "app.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-default-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.defaultWorker.command }}
          command: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.defaultWorker.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
{{ toYaml .Values.defaultWorker.containerSecurityContext | indent 12 }}
          envFrom:
          - configMapRef:
              name: {{ template "app.fullname" . }}
          - secretRef:
              name: {{ template "app.fullname" . }}
              optional: true
          - configMapRef:
              name: {{ template "app.fullname" . }}-custom
              optional: true
          - secretRef:
              name: {{ template "app.fullname" . }}-custom
              optional: true
          - configMapRef:
              name: {{ template "app.fullname" . }}-default-worker
              optional: true
          - secretRef:
              name: {{ template "app.fullname" . }}-default-worker
              optional: true
          {{- with .Values.defaultWorker.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.defaultWorker.livenessProbe }}
          livenessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.defaultWorker.readinessProbe }}
          readinessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.defaultWorker.lifecycle }}
          lifecycle: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.defaultWorker.volumeMounts }}
          volumeMounts:
          {{- tpl . $ | nindent 12 }}
          {{- end }}
    {{- with .Values.defaultWorker.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.defaultWorker.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.defaultWorker.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.defaultWorker.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.defaultWorker.volumes }}
      volumes: {{- tpl . $ | nindent 8 }}
    {{- end }}
{{- end }}