{{- if .Values.healthauthorityHsm.enabled -}}
{{- if .Values.healthauthorityHsm.envSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-healthauthority-hsm
  labels:
    app.kubernetes.io/name: {{ include "app.fullname" . }}-healthauthority-hsm
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{- toYaml .Values.healthauthorityHsm.envSecrets | nindent 2 }}
{{- end }}
{{- end }}