{{- if .Values.osirisMessageWorker.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-osiris-message-worker
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: osiris-message-worker
data:
  {{- with .Values.osirisMessageWorker.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}