{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: {{ .Values.serviceMonitor.path }}
      port: http
      interval: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.fullname" . }}
{{- end }}
