{{- if .Values.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.envSecrets | nindent 2 }}
{{- end }}
---
{{- if .Values.emptyCustomSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-custom
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData: null
{{- end }}
