---
{{- if .Values.runMigrations }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "app.fullname" . }}-run-migrations
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ template "app.fullname" . }}-run-migrations
      labels:
        {{- include "app.labels" . | nindent 8 }}
        app.kubernetes.io/component: migrations
    spec:
      restartPolicy: Never
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      - name: {{ template "app.fullname" . }}-run-migrations
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
{{ toYaml .Values.containerSecurityContext | indent 12 }}
        command: 
          - /bin/bash
        args:
          - -c
          - ./migrate && php artisan prometheus:wipe-storage
        envFrom:
        - configMapRef:
            name: {{ template "app.fullname" . }}
        - secretRef:
            name: {{ template "app.fullname" . }}
        - secretRef:
            name: {{ template "app.fullname" . }}-private-api-jwt
            optional: true
        - secretRef:
            name: {{ template "app.fullname" . }}-app
            optional: true
        - secretRef:
            name: {{ template "app.fullname" . }}-db
            optional: true
        - secretRef:
            name: {{ template "app.fullname" . }}-tih
            optional: true
        - secretRef:
            name: {{ template "app.fullname" . }}-migrations
            optional: true
        - configMapRef:
            name: {{ template "app.fullname" . }}-custom
            optional: true
        - secretRef:
            name: {{ template "app.fullname" . }}-custom
            optional: true
        {{- with .Values.volumeMounts }}
        volumeMounts:
        {{- tpl . $ | nindent 12 }}
        {{- end }}
    {{- with .Values.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.volumes }}
      volumes:
      {{- tpl . $ | nindent 8 }}
    {{- end }}
{{- end }}
