{{- if (not .Values.app.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-app
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  app-key: {{ .Values.app.key | b64enc | quote }}
{{- end }}