{{- if .Values.testResultWorker.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}-test-result-worker
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: test-result-worker
spec:
  replicas: {{ .Values.testResultWorker.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.fullname" . }}
      app.kubernetes.io/component: test-result-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.fullname" . }}
        app.kubernetes.io/component: test-result-worker
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/test-result-worker-configmap.yaml") . | sha256sum }}
        {{- range $key, $value := .Values.testResultWorker.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.testResultWorker.terminationGracePeriodSeconds }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ template "app.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-test-result-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.testResultWorker.command }}
          command: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.testResultWorker.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
{{ toYaml .Values.testResultWorker.containerSecurityContext | indent 12 }}
          envFrom:
          - configMapRef:
              name: {{ template "app.fullname" . }}
          - secretRef:
              name: {{ template "app.fullname" . }}
              optional: true
          - configMapRef:
              name: {{ template "app.fullname" . }}-custom
              optional: true
          - secretRef:
              name: {{ template "app.fullname" . }}-custom
              optional: true
          - configMapRef:
              name: {{ template "app.fullname" . }}-test-result-worker
              optional: true
          - secretRef:
              name: {{ template "app.fullname" . }}-test-result-worker
              optional: true
          {{- with .Values.testResultWorker.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.testResultWorker.livenessProbe }}
          livenessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.testResultWorker.readinessProbe }}
          readinessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.testResultWorker.lifecycle }}
          lifecycle: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.testResultWorker.volumeMounts }}
          volumeMounts:
          {{- tpl . $ | nindent 12 }}
          {{- end }}
    {{- with .Values.testResultWorker.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.testResultWorker.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.testResultWorker.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.testResultWorker.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.testResultWorker.volumes }}
      volumes: {{- tpl . $ | nindent 8 }}
    {{- end }}
{{- end }}