volumes:
    global:
    portal:
    systemtests:
    enum:
    schema:
    yarn:

services:
    test-result-worker:
        extends:
            file: docker-compose/common.yml
            service: test-result-worker
        depends_on:
            - mysql
            - redis-hap
            - rabbitmq
        volumes:
            - ./services/portal/src:/src:cached
            - ./services/shared/library:/shared/library:cached
            - ./services/shared/packages:/shared/packages:cached
            - ./services/shared/resources:/shared/resources:cached

    mysqlclient:
        extends:
            file: docker-compose/tools.yml
            service: mysqlclient

    frontend-build:
        image: node:16-bullseye
        volumes:
            - type: bind
              source: ./services
              target: /build
            - global:/build/node_modules/
            - portal:/build/portal/src/node_modules/
            - systemtests:/build/portal/systemtests/node_modules/
            - enum:/build/shared/packages/dbco-enum/node_modules/
            - schema:/build/shared/packages/schema/node_modules/
            - yarn:/build/.yarn/cache
