version: '3.7'

services:
    bridge:
        build: ./services/bridge
        environment:
            APP_ENV: test
            DEBUG: ${DEBUG:-0}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            HEALTHAUTHORITY_API_BASE_URI: http://healthauthority-api:8080/v1/
        depends_on:
            - redis
            - healthauthority-api
        networks:
            - sluice
            - healthauthority

    worker:
        build: ./services/worker
        environment:
            APP_ENV: test
            DEBUG: ${DEBUG:-0}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            HEALTHAUTHORITY_API_BASE_URI: http://healthauthority-api:8080/v1/
        depends_on:
            - redis
            - healthauthority-api
        networks:
            - sluice
            - healthauthority

    mysqlclient:
        image: mysql
        entrypoint: [ "mysql", "--host=mysql", "--user=root", "--password=$MYSQL_PASSWORD", "portal" ]
        environment:
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - healthauthority