version: '3.7'

services:
    bridge:
        extends:
            file: docker-compose/common.yml
            service: bridge
        volumes:
            - ./services/bridge/src:/src

    worker:
        extends:
            file: docker-compose/common.yml
            service: worker
        volumes:
            - ./services/worker/src:/src

    mysqlclient:
        extends:
            file: docker-compose/tools.yml
            service: mysqlclient

    simulator:
         build: services/simulator
         environment:
             APP_ENV: development
             DEBUG: ${DEBUG:-0}
             PUBLIC_API_BASE_URI: http://public-api:8080/v1/
             REDIS_HOST: redis-haa
             REDIS_PORT: 6379
         networks:
             - public
             - healthauthority