version: '3.7'

services:
    bridge:
        build: ./services/bridge
        environment:
            APP_ENV: development
            DEBUG: ${DEBUG:-0}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            HEALTHAUTHORITY_API_BASE_URI: http://healthauthority-api:8080/v1/
        volumes:
            - ./services/bridge/src:/src
        depends_on:
            - redis
            - healthauthority-api
        networks:
            - sluice
            - healthauthority

    worker:
        build: ./services/worker
        environment:
            APP_ENV: development
            DEBUG: ${DEBUG:-0}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            HEALTHAUTHORITY_API_BASE_URI: http://healthauthority-api:8080/v1/
        volumes:
            - ./services/worker/src:/src
        depends_on:
            - redis
            - healthauthority-api
        networks:
            - sluice
            - healthauthority

    mysqlclient:
        image: mysql
        entrypoint: [ "mysql", "--host=mysql", "--user=root", "--password=$MYSQL_PASSWORD", "portal" ]
        environment:
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - healthauthority

    simulator:
         build: ./services/simulator
         environment:
             APP_ENV: development
             DEBUG: ${DEBUG:-0}
             PUBLIC_API_BASE_URI: http://public-api:8080/v1/
             REDIS_HOST: redis-haa
             REDIS_PORT: 6379
         depends_on:
             - public-api
         volumes:
             - ./services/simulator/src:/src
         networks:
             - public
             - healthauthority