version: '3.7'

services:
    hsm-setup:
        build:
            context: ../nl-covid19-dbco-app-hsm-private/hsm-simulator
            dockerfile: Dockerfile.hsm-setup
        command: /setup-hsm
        environment:
            SIM_HOST: hsm
            SO_PIN: ${HSM_SO_PIN}
            USER_PIN: ${HSM_USER_PIN}
        networks:
            - healthauthority