version: '3.7'

volumes:
    hsm-data:
        driver: local

services:
    mysql:
        ports:
            - ${MYSQL_PORT:-3306}:3306

    private-api:
        environment:
            APP_ENV: development
        ports:
            - ${PRIVATE_API_PORT:-8081}:8080
        volumes:
            - ./services/shared/library:/shared/library
            - ./services/private-api/src:/src

    public-api:
        environment:
            APP_ENV: development
        ports:
            - ${PUBLIC_API_PORT:-8082}:8080
        volumes:
            - ./services/shared/library:/shared/library
            - ./services/public-api/src:/src

    bridge-clients:
        build: ./services/bridge
        environment:
            APP_ENV: development
        volumes:
            - ./services/bridge/src:/src

    bridge-caseresults:
        build: ./services/bridge
        environment:
            APP_ENV: development
        volumes:
            - ./services/bridge/src:/src

    healthauthority-api:
        environment:
            APP_ENV: development
        ports:
            - ${HEALTHAUTHORITY_API_PORT:-8083}:8080
        volumes:
            - ./services/shared/library:/shared/library
            - ./services/healthauthority-api/src:/src

    portal:
        build:
            args:
                - INSTALL_DEV_TOOLS=1
        environment:
            APP_ENV: development
        ports:
            - ${PORTAL_PORT:-8084}:8080
        volumes:
            - ./services/portal/src:/src

    healthauthority-hsm:
        build:
            context: ./services
            dockerfile: healthauthority-api/Dockerfile
        command: /src/console security:manage-keys
        environment:
            APP_ENV: development
            DEBUG: ${DEBUG:-0}
            DB_TYPE: mysql
            DB_HOST: mysql
            DB_DATABASE: portal
            DB_USERNAME: ${HEALTHAUTHORITY_API_DB_USERNAME}
            DB_PASSWORD: ${HEALTHAUTHORITY_API_DB_PASSWORD}
            DB_TNS: ${HEALTHAUTHORITY_API_DB_TNS:-oracle/XEPDB1}
            REDIS_HOST: redis-haa
            REDIS_PORT: 6379
            PRIVATE_API_BASE_URI: http://private-api:8080/v1/
            PRIVATE_API_JWT_SECRET: ${PRIVATE_API_JWT_SECRET}
            SECURITY_MODULE_USER_PIN: ${HSM_USER_PIN}
            SECURITY_MODULE_SLOT_LABEL: "CryptoServer PKCS11 Token"
        networks:
            - healthauthority
            - private
        volumes:
            - hsm-data:/hsm
            - ./services/healthauthority-api/assets/cs_pkcs11_R2_keystore.cfg:/etc/utimaco/cs_pkcs11_R2.cfg
            - ./services/healthauthority-api/src:/src
            - ./services/shared/library:/shared/library
        depends_on:
            - redis-haa
            - private-api