secrets:
    composer_auth:
        file: ./auth.json

volumes:
    mysql-data:
        driver: local

services:
    redis-sp:
        extends:
            file: docker-compose/common.yml
            service: redis-sp

    redis-hav:
        extends:
            file: docker-compose/common.yml
            service: redis-hav

    redis-hap:
        extends:
            file: docker-compose/common.yml
            service: redis-hap

    rabbitmq:
        extends:
            file: docker-compose/common.yml
            service: rabbitmq
        ports:
            - ${RABBITMQ_PORT:-5672}:5672

    mysql:
        extends:
            file: docker-compose/common.yml
            service: mysql

    portal:
        extends:
            file: docker-compose/common.yml
            service: portal
        depends_on:
            - mysql
            - redis-hav
            - redis-hap
        build:
            args:
                - DEV=1
            secrets:
                - composer_auth
        environment:
            LOG_CHANNEL: ${LOG_CHANNEL:-"null"}
        volumes:
            - ./services/portal/src:/src
            - ./services/portal/src/storage/phpunit/coverage:/src/storage/phpunit/coverage
            - ./services/shared/library:/shared/library:ro,delegated
            - ./services/shared/packages:/shared/packages:ro,delegated
            - ./services/shared/resources:/shared/resources:ro,delegated
        tmpfs:
            - /src/storage/framework/views
            - /src/storage/framework/cache

    gateway:
        extends:
            file: docker-compose/common.yml
            service: gateway
        build:
            args:
                - DEV=1
            secrets:
                - composer_auth
        environment:
            LOG_CHANNEL: ${LOG_CHANNEL:-"null"}
        volumes:
            - ./services/gateway/src:/src
            - ./services/shared/packages:/shared/packages:ro,delegated
            - ./services/shared/library:/shared/library:ro,delegated
        depends_on:
            - redis-hap
