version: '3.7'

# test overrides
services:
    private-api:
        environment:
            APP_ENV: test
        volumes:
            - ./services/shared/library:/shared/library
            - ./services/private-api/src:/src

    public-api:
        environment:
            APP_ENV: test
        volumes:
            - ./services/shared/library:/shared/library
            - ./services/public-api/src:/src

    bridge-clients:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED"

    bridge-caseresults:
        environment:
            APP_ENV: test
        command: bash -c "echo DISABLED"

    healthauthority-api:
        environment:
            APP_ENV: test
        volumes:
            - ./services/shared/library:/shared/library
            - ./services/healthauthority-api/src:/src

    portal:
        environment:
            APP_ENV: test
        volumes:
            - ./services/portal/src:/src