version: '3.7'

services:
    mysqlclient:
        image: mysql
        entrypoint: [ "mysql", "--host=mysql", "--user=root", "--password=$MYSQL_PASSWORD", "portal" ]
        environment:
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - healthauthority

    simulator:
         build: ../services/simulator
         environment:
             APP_ENV: development
             DEBUG: ${DEBUG:-0}
             PUBLIC_API_BASE_URI: http://public-api:8080/v1/
             REDIS_HOST: redis-haa
             REDIS_PORT: 6379
         networks:
             - public
             - healthauthority