services:
    mysqlclient:
        image: mysql/mysql-server:8.0.27
        entrypoint: [ "mysql", "--host=mysql", "--user=root", "--password=$MYSQL_PASSWORD", "portal" ]
        environment:
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
