GRANT ALL PRIVILEGES ON DATABASE portal TO portal;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO portal;

ALTER DEFAULT PRIVILEGES FOR ROLE portal IN SCHEMA public GRANT ALL ON TABLES TO healthauthority_api;