apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  DEBUG: {{ quote .Values.debug }}
  APACHE_RUN_USER: {{  .Values.apache.run.user }}
  REDIS_HOST: {{  .Values.redis.host }}
  REDIS_PORT: {{  quote .Values.redis.port }}
  {{- if .Values.redis.sentinel.service }}
  REDIS_SENTINEL_SERVICE: {{ .Values.redis.sentinel.service }}
  {{- end }}
  DB_TYPE: {{ .Values.db.type }}
  DB_HOST: {{ .Values.db.host }}
  DB_DATABASE: {{ .Values.db.database }}
  PRIVATE_API_BASE_URI: {{ .Values.private.api.base_uri }}