apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 30
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ template "app.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ template "app.fullname" . }}
          - secretRef:
              name: {{ template "app.fullname" . }}-db
          {{- if eq .Values.security.module.type "hsm"}}
          - secretRef:
              name: {{ template "app.fullname" . }}-hsm
          {{- end }}
          - secretRef:
              name: {{ template "app.fullname" . }}-private-api-jwt
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort | default 8080 }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- if eq .Values.security.module.type "hsm"}}
          volumeMounts:
          - name: pkcs11
            mountPath: /etc/utimaco
          {{- end }}
          livenessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
    {{- with .Values.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if eq .Values.security.module.type "hsm"}}
      volumes:
      - name: pkcs11
        secret:
          secretName: {{ template "app.fullname" . }}-pkcs11
    {{- end }}