{{- if eq .Values.security.module.type "hsm"}}
{{- if (not .Values.security.module.hsm.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-pkcs11
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  cs_pkcs11_R2.cfg: {{ .Values.security.module.hsm.pkcs11 | b64enc }}
{{- end }}
{{- end }}