{{- if (not .Values.db.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-db
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
{{- end }}