# Default values for worker

image:
  repository: ghcr.io/minvws/nl-covid19-dbco-app-backend-private/worker
  tag: 0.2.1
  pullPolicy: IfNotPresent

imagePullSecrets:

# It takes a Cron format string, such as 0 * * * * (every hour)
schedule: "0 * * * *"

successfulJobsHistoryLimit: 3

restartPolicy: OnFailure

# Allow (default): The cron job allows concurrently running jobs
# Forbid: The cron job does not allow concurrent runs; if it is time for a new job run and the previous job run hasn't finished yet, the cron job skips the new job run
# Replace: If it is time for a new job run and the previous job run hasn't finished yet, the cron job replaces the currently running job run with a new job run
concurrencyPolicy: Forbid

worker:
  args: ["questionnaire:refresh-all"]

# Redis
redis:
  host: redis-master
  port: 6379
  sentinel:
    service:

# HAA
healthauthority:
  api:
    base_uri: http://healthauthority-api:8080/v1/

# Debug
debug: 0

serviceAccount:
  # Specifies whether a service account should be created
  enabled: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 1m
    memory: 64Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}
