apiVersion: v2
version: 0.0.0
appVersion: 0.0.0
name: portal
engine: gotpl
description: Portal Helm chart for Kubernetes
home: https://github.com/minvws/nl-covid19-dbco-app-backend-private
sources:
  - https://github.com/minvws/nl-covid19-dbco-app-backend-private
