import type { IndexStoreState } from '@/store/index/indexStore';

export const fakeIndexStoreState = {
    calendarData: [],
    calendarViews: {},
    backendError: null,
    uuid: '56784158-7f32-4f93-b50e-c73276ec7f1f',
    loaded: true,
    meta: {
        uuid: '56784158-7f32-4f93-b50e-c73276ec7f1f',
        owner: '00000000-0000-0000-0000-000000000001',
        organisationUuid: '00000000-0000-0000-0000-000000000000',
        assignedUserUuid: '00000000-0000-0000-0000-000000000001',
        assignedCaseListUuid: null,
        assignedName: null,
        assignedOrganisationUuid: null,
        assignedOrganisationLabel: null,
        organisation: {
            uuid: '00000000-0000-0000-0000-000000000000',
            abbreviation: 'GGD1',
            externalId: '00000',
            hpZoneCode: '000000',
            name: 'Demo GGD1',
            phoneNumber: '0800 919988',
            bcoPhase: '1',
            bcoStatus: null,
            isCurrent: true,
        },
        bcoStatus: 'draft',
        bcoPhase: '1',
        indexStatus: 'initial',
        statusIndexContactTracing: 'new',
        statusExplanation: '',
        name: 'Francesco Cummings',
        source: null,
        caseId: 'CB1-788-054',
        testMonsterNumber: null,
        symptomatic: null,
        indexSubmittedAt: null,
        windowExpiresAt: null,
        pairingExpiresAt: null,
        exportId: null,
        exportedAt: null,
        osirisNumber: 4324490,
        completedAt: null,
        pseudoBsnGuid: null,
        schemaVersion: 5,
        priority: 0,
        caseLabels: [],
        organisationLabel: null,
        searchDateOfBirth: '1288179a09792db11e618a77aed14d38f5db1a53ab87ed54d8b54dcbb6164172',
        searchEmail: '04ad06b3b2f564183a431f8f809bc87fd1da2398046861dd305a234bd01223b1',
        searchPhone: 'cc794f5c755e9b8bbb058cd2886b49b977983c69a8f675e2479411ed5ec3923a',
        expiresAt: null,
        copiedAt: null,
        dateOfSymptomOnset: null,
        dateOfTest: null,
        createdAt: '2023-03-30T10:59:24Z',
        updatedAt: '2023-03-30T11:08:13Z',
        deletedAt: null,
        isApproved: null,
        userCanEdit: true,
        isLocked: false,
        contextContagiousCount: 44787,
        taskCount: {
            contact: 0,
            positivesource: 0,
            symptomaticsource: 0,
        },
    },
    errors: {},
    fragments: {
        general: {
            schemaVersion: 2,
            source: null,
            reference: 'CB1-788-054',
            hpzoneNumber: null,
            notes: null,
            organisation: {
                uuid: '00000000-0000-0000-0000-000000000000',
                name: 'Demo GGD1',
            },
            createdAt: '2023-03-30T10:59:24Z',
            deletedAt: null,
            pairingAllowedUntil: '2023-04-04T10:59:24+00:00',
            isPairingAllowed: true,
            expiresAt: null,
        },
        index: {
            schemaVersion: 2,
            initials: null,
            firstname: 'Francesco',
            lastname: 'Cummings',
            bsnNotes: null,
            dateOfBirth: '2008-02-07',
            gender: null,
            address: {
                schemaVersion: 1,
                postalCode: '1740GA',
                houseNumber: '45371',
                houseNumberSuffix: null,
                street: null,
                town: null,
            },
            bsnCensored: null,
            bsnLetters: null,
            hasNoBsnOrAddress: [],
        },
        contact: {
            schemaVersion: 1,
            phone: '06 12345678',
            email: 'Colten_Balistreri9@hotmail.com',
        },
        alternateContact: {
            schemaVersion: 1,
            hasAlternateContact: null,
            gender: null,
            relationship: null,
            firstname: null,
            lastname: null,
            phone: null,
            email: null,
            isDefaultContact: null,
        },
        alternativeLanguage: {
            schemaVersion: 1,
            useAlternativeLanguage: null,
            emailLanguage: null,
            phoneLanguages: null,
        },
        deceased: {
            schemaVersion: 1,
            isDeceased: 'no',
            deceasedAt: null,
            cause: null,
        },
        symptoms: {
            schemaVersion: 1,
            hasSymptoms: null,
            symptoms: null,
            otherSymptoms: null,
            wasSymptomaticAtTimeOfCall: null,
            stillHadSymptomsAt: null,
            diseaseCourse: null,
        },
        test: {
            schemaVersion: 3,
            dateOfSymptomOnset: null,
            isSymptomOnsetEstimated: false,
            dateOfTest: null,
            dateOfResult: null,
            dateOfInfectiousnessStart: null,
            otherReason: null,
            infectionIndicator: null,
            selfTestIndicator: null,
            labTestIndicator: null,
            otherLabTestIndicator: null,
            monsterNumber: null,
            selfTestLabTestDate: null,
            selfTestLabTestResult: null,
            isReinfection: null,
            previousInfectionDateOfSymptom: null,
            previousInfectionSymptomFree: null,
            previousInfectionProven: null,
            contactOfConfirmedInfection: null,
            previousInfectionReported: null,
            previousInfectionHpzoneNumber: null,
            source: null,
            testLocation: null,
            testLocationCategory: null,
            reasons: null,
        },
        vaccination: {
            schemaVersion: 3,
            isVaccinated: null,
            vaccineInjections: null,
            vaccinationCount: null,
        },
        hospital: {
            schemaVersion: 1,
            isAdmitted: null,
            name: null,
            location: null,
            admittedAt: null,
            releasedAt: null,
            reason: null,
            hasGivenPermission: null,
            practitioner: null,
            practitionerPhone: null,
            isInICU: null,
            admittedInICUAt: null,
        },
        underlyingSuffering: {
            schemaVersion: 2,
            hasUnderlyingSufferingOrMedication: null,
            hasUnderlyingSuffering: null,
            otherItems: null,
            remarks: null,
            items: null,
        },
        pregnancy: {
            schemaVersion: 2,
            isPregnant: null,
            remarks: null,
        },
        recentBirth: {
            schemaVersion: 2,
        },
        medication: {
            schemaVersion: 1,
            hasMedication: null,
            isImmunoCompromised: null,
            immunoCompromisedRemarks: null,
            hasGivenPermission: null,
            practitioner: null,
            practitionerPhone: null,
            hospitalName: null,
            medicines: null,
        },
        generalPractitioner: {
            schemaVersion: 1,
            name: null,
            practiceName: null,
            address: null,
            hasInfectionNotificationConsent: null,
        },
        alternateResidency: {
            schemaVersion: 1,
            hasAlternateResidency: null,
            address: null,
            remark: null,
        },
        housemates: {
            schemaVersion: 1,
            hasHouseMates: null,
            hasOwnFacilities: null,
            hasOwnKitchen: null,
            hasOwnBedroom: null,
            hasOwnRestroom: null,
            canStrictlyIsolate: null,
            bottlenecks: null,
        },
        riskLocation: {
            schemaVersion: 2,
            isLivingAtRiskLocation: null,
            type: null,
            otherType: null,
            hasRelatedSickness: null,
            hasDifferentDiseaseCourse: null,
        },
        job: {
            schemaVersion: 1,
            wasAtJob: null,
            sectors: null,
            professionCare: null,
            closeContactAtJob: null,
            professionOther: null,
            otherProfession: null,
            particularities: null,
        },
        eduDaycare: {
            schemaVersion: 2,
        },
        principalContextualSettings: {
            schemaVersion: 1,
            hasPrincipalContextualSettings: null,
            items: null,
            otherItems: null,
        },
        abroad: {
            schemaVersion: 1,
            wasAbroad: null,
            trips: null,
        },
        contacts: {
            schemaVersion: 2,
            shareNameWithContacts: null,
            estimatedMissingContacts: null,
            estimatedCategory1Contacts: null,
            estimatedCategory2Contacts: null,
            estimatedCategory3Contacts: null,
        },
        groupTransport: {
            schemaVersion: 1,
            withReservedSeats: null,
        },
        sourceEnvironments: {
            schemaVersion: 2,
        },
        communication: {
            schemaVersion: 3,
            otherAdviceGiven: null,
            particularities: null,
            isolationAdviceGiven: null,
            conditionalAdviceGiven: null,
            scientificResearchConsent: null,
            remarksRivm: null,
        },
        immunity: {
            schemaVersion: 2,
        },
        extensiveContactTracing: {
            schemaVersion: 3,
            receivesExtensiveContactTracing: 'standard',
            otherDescription: null,
        },
    },
    messages: [],
    contexts: [],
    tasks: {},
    testResults: [],
} as IndexStoreState;
