FROM ubuntu:18.04

ENV DEBIAN_FRONTEND="noninteractive"
ENV TZ="Europe/Amsterdam"

# Install packages and extensions
RUN apt-get -qq update && \
    apt-get -y install software-properties-common && \
    add-apt-repository ppa:ondrej/php && \
    apt-get -qq update && \
    apt-get -y install php7.4 php7.4-cli php7.4-json php7.4-zip php7.4-opcache php7.4-pgsql php7.4-mysql \
                       php7.4-curl php7.4-xml php7.4-mbstring curl git wget vim unzip libzip-dev libpq-dev libicu-dev \
                       apt-transport-https ca-certificates gnupg libaio1 \
                       vim python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

RUN a2enmod rewrite && \
    a2enmod headers && \
    a2enmod proxy && \
    a2enmod proxy_http && \
    a2enmod rewrite deflate

# Install Composer and prestissimo globally for increased performance
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    composer self-update

# Copy assets and sources
COPY assets/shared/default.conf /etc/apache2/sites-available/000-default.conf
COPY assets/shared/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh
COPY assets/shared/api.ini /usr/local/etc/php/conf.d/api.ini
COPY assets/shared/security.conf /etc/apache2/conf-available/security.conf
COPY assets/shared/apache2.conf /etc/apache2/apache2.conf
COPY assets/shared/ports.conf /etc/apache2/ports.conf
COPY assets/shared/mpm_prefork.conf /etc/apache2/mods-available/mpm_prefork.conf
COPY assets/shared/mpm_prefork_default.conf /etc/apache2/mods-available/mpm_prefork_default.conf

COPY assets/healthauthority/cs_pkcs11_R2.cfg /etc/utimaco/cs_pkcs11_R2.cfg
COPY assets/healthauthority/libcs_pkcs11_R2.so /usr/lib/utimaco/libcs_pkcs11_R2.so
ENV PKCS_MODULE=/usr/lib/utimaco/libcs_pkcs11_R2.so

COPY src/shared /shared
COPY src/healthauthority /src

RUN cd /src && composer install && \
    pip3 install python-pkcs11 && \
    usermod -u 1000 www-data

# logs should go to stdout / stderr
RUN set -ex && \
    ln -sf /proc/1/fd/1 "/var/log/syslog" && \
    ln -sf /proc/1/fd/1 "/var/log/apache2/access.log" && \
    ln -sf /proc/1/fd/2 "/var/log/apache2/error.log"

# Environment
ENV PATH $PATH:/root/.composer/vendor/bin

WORKDIR /src

EXPOSE 8080/tcp

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2ctl", "-D", "FOREGROUND"]
