name: CD

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push Private API container to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: ./api
          dockerfile: Dockefile-private
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: minvws/nl-covid19-dbco-app-backend-private/backend-private-api
          tag_with_ref: true
      - name: Push Public API container to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: ./api
          dockerfile: Dockefile-public
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: minvws/nl-covid19-dbco-app-backend-private/backend-public-api
          tag_with_ref: true
      - name: Push Console container to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: ./console
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: minvws/nl-covid19-dbco-app-backend-private/backend-console
          tag_with_ref: true
