name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build the stack
      run: docker-compose --env-file ./.env.test -p test -f docker-compose.yml -f docker-compose.test.yml up -d

    - name: Run phpunit console
      run: |
        docker-compose --env-file ./.env.test -p test -f docker-compose.yml -f docker-compose.test.yml run --rm --entrypoint=/src/vendor/bin/phpunit console

    - name: Run phpunit console
      run: |
        docker-compose --env-file ./.env.test -p test -f docker-compose.yml -f docker-compose.test.yml run --rm --entrypoint=/src/vendor/bin/phpunit api