name: CI

on: [pull_request]

env:
  POSTGRES_PASSWORD: ${{ secrets.CI_SERVICE_PASSWORD }}
  PRIVATE_API_JWT_SECRET: ${{ secrets.CI_SERVICE_PASSWORD }}
  HEALTHAUTHORITY_API_DB_PASSWORD: ${{ secrets.CI_SERVICE_PASSWORD }}
  PORTAL_DB_PASSWORD: ${{ secrets.CI_SERVICE_PASSWORD }}
  PORTAL_APP_KEY: ${{ secrets.CI_SERVICE_PASSWORD }}
  DOCKER_COMPOSE: docker-compose --env-file ./.env.ci -p test -f docker-compose.main.yml -f docker-compose.ci.yml -f docker-compose.postgres.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build / start the stack
        run: $DOCKER_COMPOSE up -d

      - name: Setup database
        run: |
          sleep 1
          $DOCKER_COMPOSE run --rm psql -c "CREATE USER portal PASSWORD '$PORTAL_DB_PASSWORD'"
          $DOCKER_COMPOSE run --rm psql -c "CREATE USER healthauthority_api PASSWORD '$HEALTHAUTHORITY_API_DB_PASSWORD'"
          $DOCKER_COMPOSE run --rm psql < $BASE_PATH/install/postgres/permissions.sql
          $DOCKER_COMPOSE run --rm --entrypoint php portal artisan migrate

      - name: Worker - Run phpunit
        run: $DOCKER_COMPOSE run --rm --entrypoint=/src/vendor/bin/phpunit worker

      - name: Private Api - Run phpunit
        run: $DOCKER_COMPOSE run --rm --entrypoint=/src/vendor/bin/phpunit private_api

      - name: Public Api - Run phpunit
        run: $DOCKER_COMPOSE run --rm --entrypoint=/src/vendor/bin/phpunit public_api

      - name: Health Authority Api - Run phpunit
        run: $DOCKER_COMPOSE run --rm --entrypoint=/src/vendor/bin/phpunit healthauthority_api
