name: release

on:
  push:
    tags: ['*']

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare
        id: prep
        run: |
          VERSION=sha-${GITHUB_SHA::8}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\//}
          fi
          echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=VERSION::${VERSION}
      - name: Push Private API container to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./api
          file: ./api/Dockerfile-private
          tags: |
            ghcr.io/minvws/nl-covid19-dbco-app-backend-private/private-api:${{ steps.prep.outputs.VERSION }}
            ghcr.io/minvws/nl-covid19-dbco-app-backend-private/private-api:latest
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.prep.outputs.VERSION }}
            org.opencontainers.image.created=${{ steps.prep.outputs.BUILD_DATE }}
      - name: Push Public API container to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./api
          file: ./api/Dockerfile-public
          tags: |
            ghcr.io/minvws/nl-covid19-dbco-app-backend-private/public-api:${{ steps.prep.outputs.VERSION }}
            ghcr.io/minvws/nl-covid19-dbco-app-backend-private/public-api:latest
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.prep.outputs.VERSION }}
            org.opencontainers.image.created=${{ steps.prep.outputs.BUILD_DATE }}
      - name: Push Health Authority API container to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./api
          file: ./api/Dockerfile-healthauthority
          tags: |
            ghcr.io/minvws/nl-covid19-dbco-app-backend-private/healthauthority-api:${{ steps.prep.outputs.VERSION }}
            ghcr.io/minvws/nl-covid19-dbco-app-backend-private/healthauthority-api:latest
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.prep.outputs.VERSION }}
            org.opencontainers.image.created=${{ steps.prep.outputs.BUILD_DATE }}
      - name: Push Portal container to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./portal
          file: ./portal/Dockerfile
          tags: |
            ghcr.io/minvws/nl-covid19-dbco-app-backend-private/portal:${{ steps.prep.outputs.VERSION }}
            ghcr.io/minvws/nl-covid19-dbco-app-backend-private/portal:latest
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.prep.outputs.VERSION }}
            org.opencontainers.image.created=${{ steps.prep.outputs.BUILD_DATE }}
      - name: Push Worker container to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./worker
          file: ./worker/Dockerfile
          tags: |
            ghcr.io/minvws/nl-covid19-dbco-app-backend-private/worker:${{ steps.prep.outputs.VERSION }}
            ghcr.io/minvws/nl-covid19-dbco-app-backend-private/worker:latest
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.prep.outputs.VERSION }}
            org.opencontainers.image.created=${{ steps.prep.outputs.BUILD_DATE }}