{{- if and (.Values.jwt.enabled) (not .Values.jwt.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-jwt
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.jwt.secret | b64enc | quote }}
{{- end }}